export { default as Register } from './Auth/Register'
export { default as Login } from './Auth/Login'
export { default as Home } from './Home'
export { default as Profile } from './User/Profile'
export { default as MyPets } from './Pet/MyPets'